config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'

  # Add a route for the "about" page
  get 'about', to: 'about#index'

  # Player routes
  resources :players, only: [:index, :show], path: 'players'

  # PlayerHome routes
  resources :player_homes, only: [:index, :show], path: 'player_homes'

  # HomeFurniture routes
  resources :home_furnitures, only: [:index, :show], path: 'home_furnitures'

  # Furniture routes
  resources :furnitures, only: [:index, :show], path: 'furnitures'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/furniture.rb
class Furniture < ApplicationRecord
  has_many :player_homes, through: :home_furniture

  validates :name, :price, :diy, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }
end

app/models/home_furniture.rb
class HomeFurniture < ApplicationRecord
  belongs_to :player_home
  belongs_to :furniture

  validates :player_home_id, :furniture_id, :amount, presence: true
  validates :amount, numericality: { greater_than: 0 }

  def remove_if_amount_zero
    return unless amount <= 0

    destroy
  end
end

app/models/player.rb
class Player < ApplicationRecord
  has_one :player_home

  validates :username, :gender, :email, :birthday, :bells, presence: true
  validate :valid_birthday

  private

  def valid_birthday
    return unless birthday.present? && birthday > Date.current

    errors.add(:birthday, "You cant be born in the future. I've tried.")
  end
end

app/models/player_home.rb
class PlayerHome < ApplicationRecord
  belongs_to :player
  has_many :home_furnitures, dependent: :destroy
  has_many :furnitures, through: :home_furniture

  validates :player_id, :size, :home_value, presence: true
  validates :size,
            inclusion: { in:      ["Small", "Medium", "Large"],
                         message: "must be Small, Medium, or Large" }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/furnitures_controller.rb
class FurnituresController < ApplicationController
  def index
    if params[:search]
      @furniture = Furniture.where("name LIKE ?", "%#{params[:search]}%").paginate(page: params[:page], per_page: 10)
    else
      @furniture = Furniture.paginate(page: params[:page], per_page: 25)
    end
  end

  def show
    @furniture = Furniture.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/home_furnitures_controller.rb
class HomeFurnituresController < ApplicationController
  def index
    @home_furnitures = HomeFurniture.all
  end

  def show
    @home_furniture = HomeFurniture.find(params[:id])
  end
end

app/controllers/player_controller.rb
class PlayerController < ApplicationController
  def index
    @players = Player.all
  end

  def show
    @player = Player.find(params[:id])
  end
end

app/controllers/player_homes_controller.rb
class PlayerHomesController < ApplicationController
  def index
    @player_homes = PlayerHome.all
  end

  def show
    @player_home = PlayerHome.find(params[:id])
  end

  def filter_furniture
    @player_home = PlayerHome.find(params[:player_home_id])
    @furniture = @player_home.furniture.where("name LIKE ?", "%#{params[:search]}%")
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    if params[:search]
      @players = Player.where("username LIKE ?", "%#{params[:search]}%")
    else
      @players = Player.all
    end
  end

  def show
    @player = Player.find(params[:id])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/furnitures_helper.rb
module FurnituresHelper
end

app/helpers/home_furnitures_helper.rb
module HomeFurnituresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/player_homes_helper.rb
module PlayerHomesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/about/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>About Us</title>
</head>
<body>
  <h1>About Our Project</h1>

  <h2>Details About Data</h2>
  <p>
    Using a CSV file we will aquire all furniture items Names, Variations, Patterns, Prices and
    if the item is craftable (DIY) from the video game Animal Crossing New Horizons. The user
    will have the ability to store said furniture items in a "Player Home". The specifics about said home
    including the homes size and value will be aquired using Faker. The Player will also have data pulled from Faker
    including Username, Gender, Email, Birthday and Bells (In game Currency).
  </p>

  <h2>Data Structure</h2>
  <p>
    The data will be structured in our application across 4 database tables:
  </p>

  <ul>
    <li>
      <strong>Players (Faker)</strong>
      <ul>
        <li>Id</li>
        <li>Username: name of the user</li>
        <li>Gender: gender of the user</li>
        <li>Email: email of user</li>
        <li>Birthday: birthday of user</li>
        <li>Bells: amount of in-game currency held by the user</li>
      </ul>
    </li>
    <li>
      <strong>PlayerHome (Faker)</strong>
      <ul>
        <li>Id</li>
        <li>Player_id: id of the user which owns the home</li>
        <li>Size: size of the home</li>
        <li>Home_value: total amount of value of furniture items within the home</li>
      </ul>
    </li>
    <li>
      <strong>HomeFurniture (Bridge table)</strong>
      <ul>
        <li>Home_id: id of home</li>
        <li>Furniture_id: id of furniture item</li>
        <li>Amount: amount of specified furniture item within the home</li>
      </ul>
    </li>
    <li>
      <strong>Furniture (CSV)</strong>
      <ul>
        <li>Id</li>
        <li>Name: name of furniture item</li>
        <li>Variation: optional variation of furniture item</li>
        <li>Pattern: optional pattern of furniture item</li>
        <li>Price: optional price of furniture item</li>
        <li>DIY: denotes if the item is craftable, or obtained through purchasing</li>
      </ul>
    </li>
  </ul>
</body>
</html>

app/views/furnitures/index.html.erb
<h1 class="mb-4 ml-10 text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl">Furniture Items</h1>

<%= form_tag(furnitures_path, method: :get, class: "search-form") do %>
  <div class="relative">
    <div class="field">
      <%= text_field_tag :search, params[:search], placeholder: "Search furniture by name...", class: "block w-11/12 p-4 pl-10 mx-auto mb-5 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
    </div>
    <div class="actions">
      <%= submit_tag "Search", class: "text-white absolute right-20 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
    </div>
  </div>
<% end %>

<table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
  <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
    <tr>
      <th class="px-6 py-3">Name</th>
      <th class="px-6 py-3">Variation</th>
      <th class="px-6 py-3">Pattern</th>
      <th class="px-6 py-3">Price</th>
      <th class="px-6 py-3">DIY</th>
    </tr>
  </thead>
  <tbody>
    <% @furniture.each do |furniture| %>
      <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
        <td class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"><%= link_to furniture.name, furniture_path(furniture), class: "md:hover:text-blue-700" %></td>
        <% if (furniture.variation != nil) then %>
          <td class="px-6 py-4"><%= furniture.variation %></td>
        <% else %>
          <td class="px-6 py-4">N/A</td>
        <% end %>
        <% if (furniture.pattern != nil) then %>
          <td class="px-6 py-4"><%= furniture.pattern %></td>
        <% else %>
          <td class="px-6 py-4">N/A</td>
        <% end %>
        <td class="px-6 py-4"><%= furniture.price %></td>
        <td class="px-6 py-4"><%= furniture.diy %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="mx-auto text-center my-4">
  <%= will_paginate @furniture, class: 'pagination' %>
</div>

app/views/furnitures/show.html.erb
<h1><%= @furniture.name %></h1>


<ul>
  <li>Variation: <%= @furniture.variation %></li>
  <li>Pattern: <%= @furniture.pattern %></li>
  <li>Price: <%= @furniture.price %></li>
  <li>DIY: <%= @furniture.diy %></li>
  <li>Created: <%= @furniture.created_at %></li>
  <li>Updated: <%= @furniture.updated_at %></li>
</ul>

app/views/home/index.html.erb
<h1>ACNH Player Homes</h1>
<p></p>
<%= link_to "About", about_path %>

app/views/home_furnitures/index.html.erb
<h1>HomeFurnitures#index</h1>
<p>Find me in app/views/home_furnitures/index.html.erb</p>

app/views/home_furnitures/show.html.erb
<h1>HomeFurnitures#show</h1>
<p>Find me in app/views/home_furnitures/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FullStackAcnh</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <nav class="bg-white border-gray-200 dark:bg-gray-900">
      <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <%= link_to 'Fullstack ACNH', root_path, class: "self-center text-2xl font-semibold whitespace-nowrap dark:text-white" %>
        <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
          <li><%= link_to 'About', about_path, class: "block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" %></li>
          <li><%= link_to 'Player', players_path, class: "block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" %></li>
          <li><%= link_to 'Furniture', furnitures_path, class: "block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" %></li>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/player_homes/index.html.erb
<h1>Player Homes</h1>

<table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
  <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
    <tr>
      <th scope="col" class="px-6 py-3">Owner</th>
      <th scope="col" class="px-6 py-3">Size</th>
      <th scope="col" class="px-6 py-3">Home Value</th>
    </tr>
  </thead>
  <tbody>
    <% @player_homes.each do |player_home| %>
      <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
        <td scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"><%= link_to player_home.player.username, player_path(player_home.player), class: "md:hover:text-blue-700" %></td>
        <td class="px-6 py-4"><%= player_home.size %></td>
        <td class="px-6 py-4"><%= player_home.home_value %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/player_homes/show.html.erb
<h1><%= @player_home.player.username %>'s Home</h1>


<ul>
  <li>Owner ID: <%= @player_home.player_id %></li>
  <li>Size: <%= @player_home.size %></li>
  <li>Home Value: <%= @player_home.home_value %></li>
  <li>Created: <%= @player_home.created_at %></li>
  <li>Updated: <%= @player_home.updated_at %></li>
</ul>

app/views/players/index.html.erb
<h1 class="mb-4 ml-10 text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl">Players</h1>

<!-- Add a search form -->
<%= form_tag(players_path, method: :get, class: "search-form") do %>
  <div class="relative">
    <div class="field">
      <%= text_field_tag :search, params[:search], placeholder: "Search players...", class: "block w-11/12 p-4 pl-10 mx-auto mb-5 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
    </div>
    <div class="actions">
      <%= submit_tag "Search", class: "text-white absolute right-20 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" %>
    </div>
  </div>
<% end %>

<table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
  <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
    <tr>
      <th class="px-6 py-3">Username</th>
      <th class="px-6 py-3">Email</th>
      <th class="px-6 py-3">Bells</th>
    </tr>
  </thead>
  <tbody>
    <% @players.each do |player| %>
      <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
        <td class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white"><%= link_to player.username, player_path(player), class: "md:hover:text-blue-700" %></td>
        <td class="px-6 py-4"><%= player.email %></td>
        <td class="px-6 py-4"><%= player.bells %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/players/show.html.erb
<h1><%= @player.username %></h1>

<div class="grid grid-cols-2">
  <div>
    <h2>Player Info</h2>
    <ul>
      <li>Gender: <%= @player.gender %></li>
      <li>Email: <%= @player.email %></li>
      <li>Birthday: <%= @player.birthday %></li>
      <li>Bells: <%= @player.bells %></li>
      <li>Created: <%= @player.created_at %></li>
      <li>Updated: <%= @player.updated_at %></li>
    </ul>
  </div>
  <div>
    <h2><%= @player.username %>'s <%= link_to "House", player_home_path(@player) %></h2>
    <ul>
      <li>Size: <%= @player.player_home.size %></li>
      <li>Value: <%= @player.player_home.home_value %></li>
    </ul>
  </div>
</div>

